name: toxicblue

description: This is my personal OS image.

base-image: ghcr.io/wayblueorg/hyprland
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - fastfetch
      - gparted
      - langpacks-ru
      - tlp
      - tlp-rdw
      - yad
      - zsh
    remove:
      # - firefox
      # - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)"
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning
      remove:
      # - org.gnome.eog

  - type: signing
