name: build-toxicblue
on:
  schedule:
    - cron: "00 05 * * *" # Создается в 5:00 UTC каждый день
    # - cron: "00 05 * * 1,2,3,4,5,6" # Создается в 5:00 UTC каждый день, кроме Воскресенья
    # - cron: "00 05 * * 0" # Создается в 5:00 UTC по Воскресеньям
  merge_group:
  push:
    branches:
      - main
      - testing
    paths-ignore: # Не перестраивайте, если изменилась только документация
    - "**.md"
  workflow_call:
  workflow_dispatch: # возможность запускать сборки вручную

jobs:
  bluebuild:
    name: Build toxicblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # запретить GH отменять все сборки матрицы, если одна не удалась
      matrix:
        recipe:
          - recipe-hyprland.yml
          - recipe-qtile.yml
          - recipe-river.yml
          - recipe-sway.yml
          - recipe-wayfire.yml
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Gather image data from recipe
        run: |
          echo "IMAGE_NAME=$(grep '^name:' ./recipes/${{ matrix.recipe }} | sed 's/^name: //')" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_VERSION=$(grep '^image-version:' ./recipes/${{ matrix.recipe }} | sed 's/^image-version: //')" >> $GITHUB_ENV
          BASE_IMAGE=$(grep '^base-image:' ./recipes/${{ matrix.recipe }} | sed 's/^base-image: //')
          echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV

      - name: Verify base image
        uses: EyeCantCU/cosign-action/verify@58722a084c82190b57863002d494c91eabbe9e79 # v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'quay.io/fedora-ostree-desktops'
          pubkey: 'https://gitlab.com/fedora/ostree/ci-test/-/raw/main/quay.io-fedora-ostree-desktops.pub'

      - name: Build toxicblue
        uses: blue-build/github-action@4d8b4df657ec923574611eec6fd7e959416c47f0 # v1.8.1
        with:
          cli_version: v0.9.10
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true # включено по умолчанию, отключите, если ваше изображение маленькое и вы хотите получить более быструю сборку
          squash: true
