name: build-toxicblue-dx
on:
  schedule:
    - cron: "00 06 * * 1" # Создается в 6:00 UTC по Понедельникам

  push:
    paths-ignore: # Не перестраивайте, если изменилась только документация
    - "**.md"

  workflow_dispatch: # возможность запускать сборки вручную

jobs:
  bluebuild:
    name: Build toxicblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # запретить GH отменять все сборки матрицы, если одна не удалась
      matrix:
        recipe:
          - recipe-hyprland-dx.yml
          - recipe-niri-dx.yml
          - recipe-qtile-dx.yml
          - recipe-river-dx.yml
          - recipe-sway-dx.yml
          - recipe-wayfire-dx.yml
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Gather image data from recipe
        run: |
          echo "IMAGE_NAME=$(grep '^name:' ./recipes/${{ matrix.recipe }} | sed 's/^name: //')" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_VERSION=$(grep '^image-version:' ./recipes/${{ matrix.recipe }} | sed 's/^image-version: //')" >> $GITHUB_ENV
          BASE_IMAGE=$(grep '^base-image:' ./recipes/${{ matrix.recipe }} | sed 's/^base-image: //')
          echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV

      - name: Verify base image
        uses: EyeCantCU/cosign-action/verify@58722a084c82190b57863002d494c91eabbe9e79 # v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'quay.io/fedora-ostree-desktops'
          pubkey: 'https://gitlab.com/fedora/ostree/ci-test/-/raw/main/quay.io-fedora-ostree-desktops.pub'

      - name: Build toxicblue
        uses: blue-build/github-action@968216e45d3f5f23de24f7804259e1384cf5f358 # v1.8.3
        with:
          cli_version: v0.9.20
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true # включено по умолчанию, отключите, если ваше изображение маленькое и вы хотите получить более быструю сборку
          squash: true