name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 00:15 UTC по Воскресеньям
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: hyprland,hyprland-dx,hyprland-nvidia-dx,hyprland-nvidia-open-dx,niri,niri-dx,niri-nvidia-dx,niri-nvidia-open-dx,qtile,qtile-dx,qtile-nvidia-dx,qtile-nvidia-open-dx,river,river-dx,river-nvidia-dx,river-nvidia-open-dx,sway,sway-dx,sway-nvidia-dx,sway-nvidia-open-dx,wayfire,wayfire-dx,wayfire-nvidia-dx,wayfire-nvidia-open-dx
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7