name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 00:15 UTC по Воскресеньям
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: base-main,hyprland,hyprland-nvidia,hyprland-nvidia-open,niri,niri-nvidia,niri-nvidia-open,qtile,qtile-nvidia,qtile-nvidia-open,river,river-nvidia,river-nvidia-open,sway,sway-nvidia,sway-nvidia-open,wayfire,wayfire-nvidia,wayfire-nvidia-open
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7